### ISSUE TITLE
Improve CLI logs

### ISSUE THREAD

**Issue by excessivecoding** [xstevenyung/thinly#4]
# TODO

- [ ] Better error display
- [ ] Display tree on discovering
- [x] Color
- [x] Progress bar
- [ ] Clear logs on reload
